### PR TITLE
implement buildsystem and drop bundled boost

### PR DESCRIPTION
**Pull request by ignatenkobrain**
bundling is a very bad idea

without buildsystem we will suck instead of do cool things

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@miit-eusytov @KyzmaNIX ping?

**Comment by miit-eusytov** [comment]
Hi, Igor.
I'm trying to build proj with meson according to instruction from README, but I've got following stacktrace:

Version: 0.24.0-research
Source dir: /home/eugene/prg/cpp/RWD-meson
Build dir: /home/eugene/prg/cpp/RWD-meson/build
Build type: native build
Project name: RWD
Native cpp compiler: c++ (gcc 4.8.3)
Found pkg-config: /usr/bin/pkg-config (0.28)
Dependency QtCore found: YES 4.8.6
Dependency QtGui found: YES 4.8.6
Dependency QtXml found: YES 4.8.6
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 183, in run
    app.generate()
  File "/usr/local/bin/meson", line 129, in generate
    intr.run()
  File "/usr/local/share/meson/interpreter.py", line 853, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/share/meson/interpreter.py", line 875, in evaluate_codeblock
    raise e
  File "/usr/local/share/meson/interpreter.py", line 869, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/share/meson/interpreter.py", line 925, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/share/meson/interpreter.py", line 1607, in assignment
    self.set_variable(var_name, value)
  File "/usr/local/share/meson/interpreter.py", line 915, in set_variable
    if re.fullmatch('[_a-zA-Z][_0-9a-zA-Z]*', varname) is None:
AttributeError: 'module' object has no attribute 'fullmatch'

what I'm doing wrong?

**Comment by ignatenkobrain** [comment]
@miit-eusytov looks like something happens with your `re` module. 
```
$ python3 -c "import re; print(re.fullmatch('t', 't'))"
<_sre.SRE_Match object; span=(0, 1), match='t'>
```

**Comment by ignatenkobrain** [comment]
@jpakkane, do you have ideas?

**Comment by jpakkane** [comment]
re.fullmatch was introduced in Python 3.4. You are probably using an older version.

**Comment by ignatenkobrain** [comment]
Yes, I just started debian 7 in docker container, installed python3 there (3.2.3) and got the same error.

@miit-eusytov you need to have python3.4

**Comment by miit-eusytov** [comment]
@ignatenkobrain , @jpakkane 
Thanks, now it works correct.

@ignatenkobrain , Odeint lib from boost 1.57 have some issues with c++11 compatibility and it doesn't not supported eigen's matrix types as state type, so why I put latest version of odeint lib in /include.

**Comment by ignatenkobrain** [comment]
> Odeint lib from boost 1.57 have some issues with c++11 compatibility
I don't see this one. Can you link bug?
> it doesn't not support eigen's matrix types as state type
can you show example?

**Comment by ignatenkobrain** [comment]
```cpp
#include <Eigen/Core>
#include <boost/numeric/odeint/stepper/runge_kutta_dopri5.hpp>
#include <iostream>

using namespace Eigen;
using namespace boost::numeric::odeint;

template<size_t N>
using vector = Matrix<double, N, 1>;

typedef vector<3> state;

int main() {

    state X0;
    X0 << 1., 2., 3.;
    state xout = X0;

    runge_kutta_dopri5<state,double,state,double,vector_space_algebra> stepper;

    // If I remove these lines, everything compiles fine
    stepper.do_step([](const state x, state dxdt, const double t) -> void {
        dxdt = x;
    }, X0, 0.0, xout, 0.01);

    std::cout << xout << std::endl;
}
```
This example works for me pretty well.

**Comment by ignatenkobrain** [comment]
@miit-eusytov I've tried some examples with odeint + eigen. All works fine.
Only to do: http://stackoverflow.com/a/22788030

That comment explains why it could not work.

**Comment by miit-eusytov** [comment]
@ignatenkobrain 
> I don't see this one. Can you link bug?
I've got following compillation message:
In file included from /usr/include/boost/numeric/odeint/stepper/runge_kutta_dopri5.hpp:22:0,
                 from ./include/RWDFramework/integrate.hpp:4,
                 from src/RWDFramework/main.cpp:1:
/usr/include/boost/numeric/odeint/util/bind.hpp:36:14: error: 'std::bind' has not been declared
 using ::std::bind;
              ^
/usr/include/boost/numeric/odeint/util/bind.hpp:37:24: error: 'placeholders' is not a namespace-name
 using namespace ::std::placeholders;

Cause /boost/numeric/odeint/util/bind.hpp haven't <functional> header. But it fixed here https://github.com/headmyshoulder/odeint-v2/blob/master/include/boost/numeric/odeint/util/bind.hpp.

**Comment by ignatenkobrain** [comment]
I have `boost-devel-1.57.0-7.fc23.x86_64`. No issues with it.

bind.hpp starts with:
```cpp
/*
 *     [begin_description]
 *     Boost bind pull the placeholders, _1, _2, ... into global
 *     namespace. This can conflict with the C++03 TR1 and C++11 
 *     std::placeholders. This header provides a workaround for 
 *     this problem.
 *     [end_description]
 *        
 *     Copyright 2012 Christoph Koke
 *     Copyright 2012 Karsten Ahnert
 *           
 *     Distributed under the Boost Software License, Version 1.0.
 *     (See accompanying file LICENSE_1_0.txt or
 *     copy at http://www.boost.org/LICENSE_1_0.txt)
 * */

#ifndef BOOST_NUMERIC_ODEINT_UTIL_BIND_HPP_INCLUDED
#define BOOST_NUMERIC_ODEINT_UTIL_BIND_HPP_INCLUDED


#include <boost/numeric/odeint/config.hpp>


#if BOOST_NUMERIC_ODEINT_CXX11 
    #include <functional>
#else
#define BOOST_BIND_NO_PLACEHOLDERS
#include <boost/bind.hpp>
#endif

namespace boost {
namespace numeric {
namespace odeint {
namespace detail {

#if BOOST_NUMERIC_ODEINT_CXX11 

using ::std::bind;
using namespace ::std::placeholders;
```

It's not patched by Fedora maintainers. So it's your distro maintainer broken it. You need to report bug instead of do bad things (bundle boost) %)

```
[brain@x1carbon build]$ ~/git/meson/meson.py ..
The Meson build system
Version: 0.24.0-research
Source dir: /home/brain/git/RWD
Build dir: /home/brain/git/RWD/build
Build type: native build
Project name: RWD
Native cpp compiler: ccache c++ (gcc 5.1.1)
Found pkg-config: /usr/bin/pkg-config (0.28)
Dependency QtCore found: YES 4.8.7
Dependency QtGui found: YES 4.8.7
Dependency QtXml found: YES 4.8.7
Dependency eigen3 found: YES 3.2.4
Dependency Boost (utility) found: YES (1.57)
Build targets in project: 2
[brain@x1carbon build]$ ninja-build -v
[1/6] ccache c++ '-pipe' '-std=c++11' '-Wall' '-Wpedantic' '-Winvalid-pch' '-Wnon-virtual-dtor' '-g' '-I/usr/include/eigen3' '-DQT_SHARED' '-I/usr/include/QtCore' '-DQT_SHARED' '-I/usr/include/QtGui' '-I/usr/include/QtCore' '-DQT_SHARED' '-I/usr/include/QtXml' '-I/usr/include/QtCore' '-IRWD.dir' '-I..' '-I.' '-MMD' '-MQ' RWD.dir/src_RWDFramework_main.cpp.o '-MF' 'RWD.dir/src_RWDFramework_main.cpp.o.d' -o RWD.dir/src_RWDFramework_main.cpp.o -c ../src/RWDFramework/main.cpp
[2/6] ccache c++ '-pipe' '-std=c++11' '-Wall' '-Wpedantic' '-Winvalid-pch' '-Wnon-virtual-dtor' '-g' '-I/usr/include/eigen3' '-DQT_SHARED' '-I/usr/include/QtCore' '-DQT_SHARED' '-I/usr/include/QtGui' '-I/usr/include/QtCore' '-DQT_SHARED' '-I/usr/include/QtXml' '-I/usr/include/QtCore' '-IRWD.dir' '-I..' '-I.' '-MMD' '-MQ' RWD.dir/src_RWDFramework_ModelConfiguration.cpp.o '-MF' 'RWD.dir/src_RWDFramework_ModelConfiguration.cpp.o.d' -o RWD.dir/src_RWDFramework_ModelConfiguration.cpp.o -c ../src/RWDFramework/ModelConfiguration.cpp
[3/6] ccache c++ '-pipe' '-std=c++11' '-Wall' '-Wpedantic' '-Winvalid-pch' '-Wnon-virtual-dtor' '-g' '-fPIC' '-Iplugins/HarmonicOscillator/OscPlugin.dir' '-I../plugins/HarmonicOscillator' '-Iplugins/HarmonicOscillator' '-MMD' '-MQ' plugins/HarmonicOscillator/OscPlugin.dir/src_models_main.cpp.o '-MF' 'plugins/HarmonicOscillator/OscPlugin.dir/src_models_main.cpp.o.d' -o plugins/HarmonicOscillator/OscPlugin.dir/src_models_main.cpp.o -c ../plugins/HarmonicOscillator/src/models/main.cpp
[4/6] ccache c++ '-pipe' '-std=c++11' '-Wall' '-Wpedantic' '-Winvalid-pch' '-Wnon-virtual-dtor' '-g' '-fPIC' '-Iplugins/HarmonicOscillator/OscPlugin.dir' '-I../plugins/HarmonicOscillator' '-Iplugins/HarmonicOscillator' '-MMD' '-MQ' plugins/HarmonicOscillator/OscPlugin.dir/src_models_create_model.cpp.o '-MF' 'plugins/HarmonicOscillator/OscPlugin.dir/src_models_create_model.cpp.o.d' -o plugins/HarmonicOscillator/OscPlugin.dir/src_models_create_model.cpp.o -c ../plugins/HarmonicOscillator/src/models/create_model.cpp
[5/6] ccache c++   -o plugins/HarmonicOscillator/libOscPlugin.so plugins/HarmonicOscillator/OscPlugin.dir/src_models_create_model.cpp.o plugins/HarmonicOscillator/OscPlugin.dir/src_models_main.cpp.o '-shared' '-fPIC' '-Wl,-soname,libOscPlugin.so' '-Wl,-rpath,/home/brain/git/RWD/build/plugins/HarmonicOscillator' 
[6/6] ccache c++   -o RWD RWD.dir/src_RWDFramework_ModelConfiguration.cpp.o RWD.dir/src_RWDFramework_main.cpp.o '-ldl' '-lQtCore' '-lQtGui' '-lQtCore' '-lQtXml' '-lQtCore' 
```

**Comment by miit-eusytov** [comment]
Oops, I gave wrong boost version, I'm use boost-devel.x86_64-1.54.0-12.fc20

**Comment by ignatenkobrain** [comment]
It should work with 1.55. F21 contains it. F20 will be orphaned after 2 months, so use F21 ;)

**Comment by ignatenkobrain** [comment]
I wrote post about including 3rd party dependencies. Currently I'm working
to get a bit better solution for those wrap files, so I will provide new
patch if boost less than compatible with eigen - download odeint. Please
wait for 1-2 weeks.

https
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>
://
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>
blogs.gnome.org
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>
/ignatenko/2015/05/21/
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>
meson-and-3rd-party-dependencies-only-one-correct-way
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>
/
<https://www.google.com/url?q=https%3A%2F%2Fblogs.gnome.org%2Fignatenko%2F2015%2F05%2F21%2Fmeson-and-3rd-party-dependencies-only-one-correct-way%2F&sa=D&sntz=1&usg=AFQjCNFlGVTqoZcosgQLPgTjL4Wmab5-3w>

**Comment by ignatenkobrain** [comment]
@miit-eusytov I've updated pull request with added downloading odeint 1.57.0 if we don't have boost-devel in system. Take a look screenshot. You need to get 0.24.0 version of meson.
screenshot from 2015-05-25 11-45-47

Unfortunately `>=1.57` doesn't work with meson in this time, but I will get it fixed in some days. So just change `boost` to something other to pull new version in runtime.

**Pull request merged**
